#!/usr/bin/env python

from gevent import monkey

monkey.patch_all()


from jirc import Jirc

from objdict import ObjDict

import pprint
import logging
import signal

logger = logging.getLogger()
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)


import local_settings
settings = ObjDict(filter(lambda (k,v): k.isupper(), vars(local_settings).items()))



def main():
    signal.signal(signal.SIGABRT, shutdown)

    jirc = Jirc(settings)
    try:
        jirc.loop()
    except:
        pass

    shutdown()
   

def shutdown(sig=None, frame=None):
    jirc.disconnect()



if __name__ == '__main__':
    main()

