#!/usr/bin/env python


from jirc import Jirc

import pprint
import logging

logger = logging.getLogger()
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)


import local_settings



if __name__ == '__main__':

    jirc = Jirc(local_settings)
    jirc.connect()

    running = True
    try:
        while running:
            running = jirc.tick()
    except KeyboardInterrupt:
        pass

